using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Sample.Service.Migrations;

/// <inheritdoc />
public partial class ChangedIdToBeAutoGeneratedOnAdd : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
    }
}
